# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "jessie-chef-solo-vbox-vagrant.box"
  config.vm.synced_folder "chef-solo", "/home/vagrant/chef-solo"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
    # Customize the amount of memory on the VM:
    #vb.memory = "512"
  end
end
